In [2]:
#%% Data imputation
import numpy as np
from sklearn.impute import SimpleImputer
import scipy.sparse as sp
import pandas as pd

In [34]:
imp = SimpleImputer(missing_values=np.nan, strategy = 'most_frequent') #fill_value=0) #mean, median, constant
imp.fit([[1, 2], 
         [np.nan, 3], 
         [1, 2], 
         [7, 6]])
print(imp.statistics_)

[1. 2.]

In [32]:

X = np.array([[np.nan, 2], 
              [6, np.nan], 
              [7, 6]])
print(X)
X=imp.transform(X)
print(X)

[[nan  2.]
 [ 6. nan]
 [ 7.  6.]]
[[0. 2.]
 [6. 0.]
 [7. 6.]]

In [4]:
Y = np.array([[np.nan, 2], [np.nan, np.nan], [7, 6], [7, np.nan]])
print(Y)

[[nan  2.]
 [nan nan]
 [ 7.  6.]
 [ 7. nan]]

In [5]:
Y=imp.transform(Y)
print(Y)

[[1. 2.]
 [1. 2.]
 [7. 6.]
 [7. 2.]]

In [11]:

#%% scattered matrix
X = sp.csc_matrix([[-1, -1], [0, -1], [8, 4]])
print(X)

  (0, 0)	-1
  (2, 0)	8
  (0, 1)	-1
  (1, 1)	-1
  (2, 1)	4

In [12]:
imp2 = SimpleImputer(missing_values=-1, strategy='mean')
imp2.fit(X)
print(X)
print(imp2.statistics_)

  (0, 0)	-1
  (2, 0)	8
  (0, 1)	-1
  (1, 1)	-1
  (2, 1)	4
[4. 4.]

In [13]:
X_test = sp.csc_matrix([[-1, 2], [6, -1], [7, 6]])
print(X_test)
print(imp2.transform(X_test).toarray())

  (0, 0)	-1
  (1, 0)	6
  (2, 0)	7
  (0, 1)	2
  (1, 1)	-1
  (2, 1)	6
[[4. 2.]
 [6. 4.]
 [7. 6.]]

In [14]:
#%% most_frequent
df = pd.DataFrame([["a", "x"],
                   [np.nan, "y"],
                   ["a", np.nan],
                   ["b", "y"]], dtype="category")
df.head()

     0    1
0    a    x
1  NaN    y
2    a  NaN
3    b    y

In [17]:
imp3 = SimpleImputer(strategy="most_frequent")
df2 = imp3.fit_transform(df)
print(df2)
print(type(df2))

[['Y' 'N' 'Y' 'N']
 ['Y' 'N' '?' 'N']
 ['Y' 'N' 'Y' '?']
 ['?' 'N' 'Y' 'Y']]
<class 'numpy.ndarray'>

In [22]:
#%%
A = np.array([["Y","N","Y","N"],
              ["Y","N","?","N"],
              ["Y","N","Y","?"],
              ["?","N","Y","Y"]])
df = pd.DataFrame(A,columns=["Airconditioning","Garage","Pool","Verandah"])
df.head()

  Airconditioning Garage Pool Verandah
0               Y      N    Y        N
1               Y      N    ?        N
2               Y      N    Y        ?
3               ?      N    Y        Y

In [23]:

imp4 = SimpleImputer(missing_values="?", strategy='most_frequent')
df2 = pd.DataFrame(imp4.fit_transform(df))
df2.head()

   0  1  2  3
0  Y  N  Y  N
1  Y  N  Y  N
2  Y  N  Y  N
3  Y  N  Y  Y

In [24]:
#%%
A = np.array([["Y","N","Y","N"],
              ["Y","N","NA","N"],
              ["Y","N","Y","Y"],
              ["NA","N","Y","Y"]])
print(A)
df = pd.DataFrame(A,columns=["Airconditioning","Garage","Pool","Verandah"])
print(df.head())

[['Y' 'N' 'Y' 'N']
 ['Y' 'N' 'NA' 'N']
 ['Y' 'N' 'Y' 'Y']
 ['NA' 'N' 'Y' 'Y']]
  Airconditioning Garage Pool Verandah
0               Y      N    Y        N
1               Y      N   NA        N
2               Y      N    Y        Y
3              NA      N    Y        Y

In [25]:

imp = SimpleImputer(missing_values="NA", strategy='most_frequent')
df2 = pd.DataFrame(imp.fit_transform(df))
df2.head()

   0  1  2  3
0  Y  N  Y  N
1  Y  N  Y  N
2  Y  N  Y  Y
3  Y  N  Y  Y

In [26]:

#%% K-mean Algorithm
from sklearn.impute import KNNImputer #KNNImpute machine learning based K-mean algorithm
nan = np.nan
X = np.array([[1, 0, nan], 
              [3, 5, 1], 
              [nan, 6, 5], 
              [8, 8, nan]])
print(X)

[[ 1.  0. nan]
 [ 3.  5.  1.]
 [nan  6.  5.]
 [ 8.  8. nan]]

In [30]:

imp = KNNImputer(n_neighbors=1, weights="uniform")
X=imp.fit_transform(X)
print(X)

[[1.  0.  3. ]
 [3.  5.  1. ]
 [5.5 6.  5. ]
 [8.  8.  3. ]]